Завдання 1

Імпорт NumPy

In [23]:
import numpy as np

Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [24]:
array = np.arange(1, 11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [25]:
matrix = np.zeros((3, 3))
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [26]:
matrix = np.random.randint(1, 11, (5, 5))
matrix

array([[10,  7,  7,  7,  8],
       [10,  4,  5,  2,  9],
       [ 4,  1,  4, 10,  2],
       [ 9,  9,  9,  8,  9],
       [10,  2,  7,  2,  4]], dtype=int32)

Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [27]:
matrix = np.random.rand(4, 4)
matrix

array([[0.26511326, 0.89690912, 0.35534849, 0.45096145],
       [0.72442507, 0.76544173, 0.55023704, 0.5263121 ],
       [0.15413884, 0.88907282, 0.28717538, 0.59745518],
       [0.45707262, 0.92832997, 0.27683176, 0.95933901]])

Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [28]:
a = np.random.randint(1, 11, 5)
b = np.random.randint(1, 11, 5)

a, b, a + b, a - b, a * b

(array([6, 9, 6, 6, 3], dtype=int32),
 array([4, 7, 9, 6, 2], dtype=int32),
 array([10, 16, 15, 12,  5], dtype=int32),
 array([ 2,  2, -3,  0,  1], dtype=int32),
 array([24, 63, 54, 36,  6], dtype=int32))

Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [29]:
a = np.random.randint(1, 10, 7)
b = np.random.randint(1, 10, 7)

np.dot(a, b)

np.int32(196)

Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [30]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 3))

np.dot(a, b)

array([[ 24,   9,  16],
       [102,  42,  66]], dtype=int32)

Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [31]:
matrix = np.random.randint(1, 11, (3, 3))
np.linalg.inv(matrix)

array([[ 0.13207547, -0.0754717 ,  0.0754717 ],
       [ 1.24528302, -0.28301887, -0.71698113],
       [-1.22641509,  0.41509434,  0.58490566]])

Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [32]:
matrix = np.random.rand(4, 4)
matrix.T

array([[0.01866754, 0.59944774, 0.94852316, 0.59201157],
       [0.42028423, 0.19262715, 0.56705306, 0.31653101],
       [0.88414688, 0.47752039, 0.9568159 , 0.33108563],
       [0.37731773, 0.99698937, 0.85796885, 0.53692706]])

Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [33]:
matrix = np.random.randint(1, 11, (3, 4))
vector = np.random.randint(1, 11, 4)

np.dot(matrix, vector)

array([128, 106,  65], dtype=int32)

Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [34]:
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)

np.dot(matrix, vector)

array([1.11601585, 1.06442052])

Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [35]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 2))

a * b

array([[40,  8],
       [ 1,  5]], dtype=int32)

Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [36]:
matrix = np.random.randint(1, 101, (5, 5))
np.sum(matrix)

np.int64(1232)

Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [37]:
a = np.random.randint(1, 11, (4, 4))
b = np.random.randint(1, 11, (4, 4))

a - b

array([[ 1, -1,  7, -5],
       [-5,  0,  0,  4],
       [ 9, -6,  3, -5],
       [-1, -3,  1,  0]], dtype=int32)

Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [38]:
matrix = np.random.rand(3, 3)
np.sum(matrix, axis=1).reshape(-1, 1)

array([[2.67779847],
       [0.94098165],
       [1.82361946]])

Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [39]:
matrix = np.random.randint(1, 10, (3, 4))
matrix ** 2

array([[ 9, 16, 25, 81],
       [16, 81,  9,  1],
       [ 4,  9, 49,  1]], dtype=int32)

Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [40]:
vector = np.random.randint(1, 51, 4)
np.sqrt(vector)

array([5.74456265, 7.        , 1.        , 6.08276253])

Завдання 2

Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками

In [42]:
arr = np.arange(10)
arr = arr.reshape(2, -1)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально



In [43]:
a = np.array([[3, 2], [8, 4]])
b = np.array([[5, 6], [7, 8]])
vertical = np.vstack((a, b))
vertical

array([[3, 2],
       [8, 4],
       [5, 6],
       [7, 8]])

Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])

Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [44]:
a = np.array([1,2,3])
pattern = np.hstack((np.repeat(a, 3), np.tile(a, 3)))
pattern

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Отримайте спільні елементи між a і b

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

In [45]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.intersect1d(a, b)
common

array([2, 4])

Отримайте позиції перших 5 максимальних значень у заданому масиві a

np.random.seed(100) a = np.random.uniform(1,50, 20)

In [46]:
np.random.seed(100) 
a = np.random.uniform(1,50, 20)
indices = np.argsort(a)[-5:]
indices

array([18,  7,  3, 10, 15])

Вилучіть усі значення NaN із одновимірного масиву

а=np.array([1,2,3,np.nan,5,6,7,np.nan])

In [47]:

а=np.array([1,2,3,np.nan,5,6,7,np.nan])
clean = a[~np.isnan(a)]
clean

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

Обчисліть евклідову відстань між двома масивами a і b.

a = np.array([1,2,3,4,5]) b = np.array([4,5,6,7,8])

In [48]:
a = np.array([1,2,3,4,5]) 
b = np.array([4,5,6,7,8])
distance = np.sqrt(np.sum((a - b) ** 2))
distance

np.float64(6.708203932499369)

Знайдіть індекс 5-го повторення числа 1 у масиві x

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [50]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indices = np.where(x == 1)[0]
indices[4]

np.int64(8)

Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.